// <auto-generated />
using MVC02.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC02.Migrations
{
    [DbContext(typeof(ITIDBContext))]
    partial class ITIDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC02.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            DeptId = 1,
                            Hours = 30,
                            MinDegree = 50,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            DeptId = 1,
                            Hours = 25,
                            MinDegree = 50,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            DeptId = 2,
                            Hours = 40,
                            MinDegree = 60,
                            Name = "CCNA"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100,
                            DeptId = 3,
                            Hours = 20,
                            MinDegree = 50,
                            Name = "Recruitment"
                        },
                        new
                        {
                            Id = 5,
                            Degree = 100,
                            DeptId = 4,
                            Hours = 45,
                            MinDegree = 65,
                            Name = "Ethical Hacking"
                        },
                        new
                        {
                            Id = 6,
                            Degree = 100,
                            DeptId = 5,
                            Hours = 50,
                            MinDegree = 70,
                            Name = "Machine Learning"
                        });
                });

            modelBuilder.Entity("MVC02.Models.CrsResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Crs_Id")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("CrsResults", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crs_Id = 1,
                            Degree = 85,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Crs_Id = 2,
                            Degree = 90,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Crs_Id = 1,
                            Degree = 75,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Crs_Id = 3,
                            Degree = 60,
                            TraineeId = 7
                        },
                        new
                        {
                            Id = 5,
                            Crs_Id = 4,
                            Degree = 88,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 6,
                            Crs_Id = 5,
                            Degree = 95,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 7,
                            Crs_Id = 6,
                            Degree = 70,
                            TraineeId = 6
                        },
                        new
                        {
                            Id = 8,
                            Crs_Id = 6,
                            Degree = 98,
                            TraineeId = 8
                        });
                });

            modelBuilder.Entity("MVC02.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Ali",
                            Name = "SD"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Mona",
                            Name = "Network"
                        },
                        new
                        {
                            Id = 3,
                            Manager = "Samir",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 4,
                            Manager = "Khaled",
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = 5,
                            Manager = "Youssef",
                            Name = "AI"
                        });
                });

            modelBuilder.Entity("MVC02.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Crs_id")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Crs_id");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            Crs_id = 1,
                            DeptId = 1,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Hassan",
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            Crs_id = 2,
                            DeptId = 2,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Nour",
                            Salary = 9000m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            Crs_id = 3,
                            DeptId = 2,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Noura",
                            Salary = 10000m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo",
                            Crs_id = 4,
                            DeptId = 3,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Mahmoud",
                            Salary = 11000m
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tanta",
                            Crs_id = 5,
                            DeptId = 4,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Yara",
                            Salary = 12000m
                        },
                        new
                        {
                            Id = 6,
                            Address = "Giza",
                            Crs_id = 6,
                            DeptId = 5,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Mostafa",
                            Salary = 15000m
                        });
                });

            modelBuilder.Entity("MVC02.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Trainees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            DeptId = 1,
                            Grade = 3,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            DeptId = 2,
                            Grade = 2,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Sara"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            DeptId = 1,
                            Grade = 4,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura",
                            DeptId = 3,
                            Grade = 1,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Mariam"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tanta",
                            DeptId = 4,
                            Grade = 2,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Yassin"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Cairo",
                            DeptId = 5,
                            Grade = 3,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Salma"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Giza",
                            DeptId = 2,
                            Grade = 4,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Karim"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Alex",
                            DeptId = 5,
                            Grade = 1,
                            ImageUrl = "/Images/1.jpg",
                            Name = "Nada"
                        });
                });

            modelBuilder.Entity("MVC02.Models.Course", b =>
                {
                    b.HasOne("MVC02.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC02.Models.CrsResult", b =>
                {
                    b.HasOne("MVC02.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVC02.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("MVC02.Models.Instructor", b =>
                {
                    b.HasOne("MVC02.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Crs_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVC02.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC02.Models.Trainee", b =>
                {
                    b.HasOne("MVC02.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
